/*
* These are all the actions we can perform
* ****************************************/
export const ActionTypes = {

    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",

    SET_ORDERS: "SET_ORDERS",
    SELECTED_ORDERS: "SELECTED_ORDERS",
    REMOVE_SELECTED_ORDER : "REMOVE_SELECTED_ORDER",

    SET_IPHONES: "SET_IPHONES",
    SELECTED_IPHONES: "SELECTED_IPHONES",
    REMOVE_SELECTED_IPHONE : "REMOVE_SELECTED_IPHONE"

}

